function [pa,pb] = two_wave_seg_len(x,t1,t2,m,mu)

% Comptues the PDF of segment lengths for the two-wave admixture model
% Usage:
% x: a vector of segment lengths where the PDFs will be avaluated (Morgans)
% t1: time of first admixture event (generations ago; A and B)
% t2: time of second admixture event (generations ago; A and the existing population)
% m: the proportion of A ancestry that enters the population at the time of the first admixture, t1 generations ago (the rest is B ancestry)
% mu: the proportion of A ancestry that enters the population at the time of the second admixture, t2 generations ago (the rest is the existing ancestry)
% Output:
% pa: the PDF of A segments; pb: the PDF of B segments
% Note that the PDFs should satisfy sum(pa*dx)=sum(pb*dx)=1, where dx is the distance between points in x (for dx->0)

pa = (-1).*exp(1).^((-1/2).*x.*(t1+(-1).*m.*t1+t2+((-1)+m).*t2.*mu)).*(( ...
  -1)+m).*(t2.*mu+m.*(t1+(-1).*t2.*mu)).^(-1).*(4.*t1.*t2.*((-1)+m+mu+( ...
  -1).*m.*mu)+(t1+(-1).*m.*t1+t2+((-1)+m).*t2.*mu).^2).^(-1/2).*(((-1) ...
  .*t2.^2.*((-1)+mu).*mu+m.*(t1+(-1).*t2.*mu).^2).*(4.*t1.*t2.*((-1)+m+ ...
  mu+(-1).*m.*mu)+(t1+(-1).*m.*t1+t2+((-1)+m).*t2.*mu).^2).^(1/2).* ...
  cosh((1/2).*x.*(4.*t1.*t2.*((-1)+m+mu+(-1).*m.*mu)+(t1+(-1).*m.*t1+ ...
  t2+((-1)+m).*t2.*mu).^2).^(1/2))+((-1).*t2.^2.*(t1+t2.*((-1)+mu)).*( ...
  (-1)+mu).*mu+m.^2.*(t1+(-1).*t2.*mu).^3+(-1).*m.*(t1+(-1).*t2.*mu).*( ...
  t1.^2+(-1).*t1.*t2+2.*t2.^2.*((-1)+mu).*mu)).*sinh((1/2).*x.*(4.* ...
  t1.*t2.*((-1)+m+mu+(-1).*m.*mu)+(t1+(-1).*m.*t1+t2+((-1)+m).*t2.*mu) ...
  .^2).^(1/2)));

pb = exp(1).^((-1).*t1.*x.*(1+(-1).*(1+(-1).*m).*(1+(-1).*t1.^(-1).* ...
  t2.*mu))).*t1.*(1+(-1).*(1+(-1).*m).*(1+(-1).*t1.^(-1).*t2.*mu));
